import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {chromium} from '@playwright/test';import {expectedHistories} from '../src/fixture.mjs';
const out=path.resolve('test-results/browser');await fs.mkdir(out,{recursive:true});const html=await fs.readFile('dist/index.html');const server=http.createServer((req,res)=>{if(['/','/route-leaf/','/route-leaf/index.html'].includes(req.url)){res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html);}else{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(4178,'127.0.0.1',r));const browser=await chromium.launch({headless:true,chromiumSandbox:true,...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{})});const session=await browser.newBrowserCDPSession(),command=await session.send('Browser.getBrowserCommandLine');assert(!command.arguments.some(x=>x==='--no-sandbox'||x==='--disable-setuid-sandbox'));await fs.writeFile(path.join(out,'browser-command.json'),JSON.stringify(command,null,2));const report={sandbox:true,cases:[],screenshots:[],downloads:[]},errors=[],external=[];const context=await browser.newContext({viewport:{width:1440,height:1080},acceptDownloads:true});await context.tracing.start({screenshots:true,snapshots:true,sources:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4178')&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});const url='http://127.0.0.1:4178/route-leaf/';
async function shot(name,p=page){await p.screenshot({path:path.join(out,name+'.png'),fullPage:true});report.screenshots.push(name+'.png');}
async function check(name,fn){await fn();report.cases.push(name);console.log('PASS',name);}
async function sample(p=page,ui='en',form='English (en)'){await p.goto(url);await p.locator('#language').selectOption(ui);await p.locator('#sample').click();await p.locator('#compile:not([disabled])').waitFor();await p.locator('#form-language').selectOption(form);await p.locator('#compile').click();await p.locator('#results:not([hidden])').waitFor();}
async function download(selector,name,p=page){const wait=p.waitForEvent('download');await p.locator(selector).click();const d=await wait;const dest=path.join(out,name);await d.saveAs(dest);assert.equal(await d.failure(),null);report.downloads.push(name);return dest;}
try{
await check('Japanese empty state and keyboard skip link',async()=>{await page.goto(url);await page.keyboard.press('Tab');assert.equal(await page.locator('.skip').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Enter');assert.equal(await page.locator('#workspace').evaluate(e=>e===document.activeElement),true);assert(await page.locator('#compile').isDisabled());await shot('01-ja-empty');});
await check('Sample compile exact counts and contextual variants',async()=>{await sample();assert.deepEqual(await page.locator('.stat strong').allTextContents(),['9','6','12','6','1']);await page.locator('#card-details').evaluate(e=>e.open=true);assert.equal(await page.locator('.mini-card').count(),12);await shot('02-en-cards');});
await check('Actual JSON HTML answer sheet and PDF downloads',async()=>{const routeFile=await download('#download-routes','workshop-en.routes.json');const m=JSON.parse(await fs.readFile(routeFile));assert.equal(m.cards.length,12);await download('#download-html','workshop-en-booklet.html');await download('#download-answers','workshop-en-answer-sheet.html');await download('#download-pdf','workshop-en.pdf');assert((await fs.readFile(path.join(out,'workshop-en.pdf'))).subarray(0,4).equals(Buffer.from('%PDF')));});
await check('All six walkthroughs match expected visited sources and END',async()=>{for(const h of expectedHistories){await page.locator('#restart').click();const visited=[];while(await page.locator('#active-card').getAttribute('data-card')!=='END'){const meta=await page.locator('.active-meta').textContent(),source=meta.split(' / ').at(-1);visited.push(source);const choice=h.answers[source];if(choice)await page.locator(`#active-card button[data-value="${choice}"]`).click();else await page.locator('#active-card button').first().click();assert(visited.length<=9);}assert.deepEqual(visited,h.questions);assert.equal(await page.locator('#trace li').count(),h.questions.length);}await shot('03-en-complete');});
await check('Restart clears earlier routing context',async()=>{await page.locator('#restart').click();assert.equal(await page.locator('#active-card').getAttribute('data-card'),'C01');assert.equal(await page.locator('#trace li').count(),0);await page.locator('[data-value="book"]').click();await page.locator('[data-value="no"]').click();assert.match(await page.locator('.active-meta').textContent(),/book_experience/);});
await check('Questionnaire language changes invalidate prior output',async()=>{await page.locator('#form-language').selectOption('日本語 (ja)');assert(await page.locator('#results').isHidden());await page.locator('#compile').click();await page.locator('#results:not([hidden])').waitFor();assert.equal(await page.locator('.active-title').textContent(),'参加するワークショップは？');await download('#download-routes','workshop-ja.routes.json');await download('#download-pdf','workshop-ja.pdf');await download('#download-html','workshop-ja-booklet.html');await page.locator('#language').selectOption('ja');await shot('04-ja-ready');});
await check('UI localization preserves current interview without changing source language',async()=>{await page.locator('[data-value="print"]').click();const id=await page.locator('#active-card').getAttribute('data-card');await page.locator('#language').selectOption('en');assert.equal(await page.locator('#active-card').getAttribute('data-card'),id);assert.equal(await page.locator('#trace li').count(),1);assert.match(await page.locator('.active-title').textContent(),/道具/);});
await check('Malformed file removes stale output and disables compile',async()=>{await page.locator('#source-input').setInputFiles({name:'invalid.xlsx',mimeType:'application/octet-stream',buffer:Buffer.from('not a zip')});await page.locator('#notice.error').waitFor();assert(await page.locator('#results').isHidden());assert(await page.locator('#compile').isDisabled());await shot('05-en-error');});
await check('Reset clears uploaded file and all derived state',async()=>{await page.locator('#source-input').setInputFiles('generated/workshop.xlsx');await page.locator('#compile:not([disabled])').waitFor();await page.locator('#reset').click();assert(await page.locator('#compile').isDisabled());assert(await page.locator('#results').isHidden());assert.equal(await page.locator('#source-input').evaluate(e=>e.files.length),0);assert.equal(await page.locator('#form-language option').count(),0);});
await check('Latest input wins against interrupted sample/reset flow',async()=>{await page.locator('#sample').click();await page.locator('#reset').click();await page.waitForTimeout(150);assert(await page.locator('#compile').isDisabled());assert(await page.locator('#results').isHidden());});
await check('Mobile Japanese and English ready/error states have no overflow',async()=>{const phone=await context.newPage();await phone.setViewportSize({width:390,height:844});await sample(phone,'ja','日本語 (ja)');assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('06-ja-mobile',phone);await phone.locator('#language').selectOption('en');await phone.locator('#card-details').evaluate(e=>e.open=true);assert(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await shot('07-en-mobile',phone);await phone.close();});
assert.deepEqual(errors,[]);assert.deepEqual(external,[]);report.pageErrors=errors;report.externalRequests=external;report.ok=true;
}catch(e){report.ok=false;report.error=e.stack;await shot('failure').catch(()=>{});throw e;}finally{await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2));await context.tracing.stop({path:path.join(out,'trace.zip')});await browser.close();await new Promise(r=>server.close(r));}
