import {test} from 'node:test';import assert from 'node:assert/strict';import {compileTables,parseForm,compileForm,parseRelevance,evaluate} from '../src/core.mjs';import {workshop,expectedHistories} from '../src/fixture.mjs';
const copy=()=>structuredClone(workshop), sort=h=>h.map(x=>JSON.stringify({answers:Object.fromEntries(Object.entries(x.answers).sort()),questions:x.questions})).sort();
const rejects=(change,code)=>{const w=copy();change(w);assert.throws(()=>compileTables(w,'English (en)'),e=>e.code===code);};
test('exact workshop: six reachable histories, 12 cards, six booklet pages',()=>{const m=compileTables(workshop,'English (en)');assert.deepEqual(m.counts,{questions:9,histories:6,cards:12,pages:6,answerSheetPages:1});assert.deepEqual(sort(m.histories),sort(expectedHistories));for(const q of ['loan','print_experience','book_experience'])assert.equal(m.cards.filter(c=>c.source===q).length,2);assert.equal(m.cards.filter(c=>c.source==='pickup').length,1);});
test('every edge is forward and points to a real card or END',()=>{const m=compileTables(workshop);for(const c of m.cards)for(const id of c.options?.map(x=>x.next)||[c.next])assert(id==='END'||m.cards.findIndex(x=>x.id===id)>m.cards.indexOf(c));});
test('Japanese selection preserves Unicode labels',()=>{const m=compileTables(workshop,'日本語 (ja)');assert.equal(m.cards[0].label,'参加するワークショップは？');assert.equal(m.cards[0].options[1].label,'製本');});
test('skipped controller stays unanswered',()=>{const m=compileTables(workshop);for(const h of m.histories.filter(h=>h.answers.loan==='no'))assert(!Object.hasOwn(h.answers,'pickup'));});
test('non-routing answer dimensions do not multiply histories',()=>{const w=copy();for(let i=0;i<20;i++)w.survey.push(['select_one yesno',`extra_${i}`,'Extra','追加','','','yes','']);assert.equal(compileTables(w).counts.histories,6);});
test('nested conditional groups combine with question conditions',()=>{const w=copy();w.survey.splice(3,0,['begin_group','g','Group','組','','','','${loan} = \'yes\'']);w.survey.splice(5,0,['begin_group','inner','Inside','中','','','','${track} = \'book\'']);w.survey.splice(7,0,['end_group','','','','','','',''],['end_group','','','','','','','']);const m=compileTables(w);for(const h of m.histories.filter(h=>h.answers.loan==='no'))assert(!h.questions.includes('print_experience')&&!h.questions.includes('book_experience'));});
test('precedence and parentheses are parsed without eval',()=>{const f=parseForm(workshop);const p=new Map(f.questions.map(q=>[q.name,q]));assert(evaluate(parseRelevance("${track} = 'print' or ${loan} = 'yes' and ${pickup} = 'morning'",p).ast,{track:'print'}));assert(!evaluate(parseRelevance("(${track} = 'print' or ${loan} = 'yes') and ${pickup} = 'morning'",p).ast,{track:'print'}));});
test('duplicate labels with different codes remain distinct',()=>{const w=copy();w.choices[2][2]='Print';const m=compileTables(w);assert.deepEqual(m.cards[0].options.map(x=>x.value),['print','book']);assert.equal(m.counts.histories,6);});
test('unreachable question remains on answer sheet and is reported',()=>{const w=copy();w.survey[9][7]="${track} = 'print' and ${track} = 'book'";const m=compileTables(w);assert.deepEqual(m.unreachable,['final_comment']);assert.equal(m.questions.length,9);assert(!m.cards.some(c=>c.source==='final_comment'));});
for(const [label,change,code] of [
 ['repeat',w=>w.survey[1][0]='begin_repeat','unsupported_type'],['calculation',w=>{w.survey[0].push('calculation');w.survey[1].push('1+1');},'unsupported_column'],['default',w=>{w.survey[0].push('default');w.survey[1].push('print');},'unsupported_column'],['constraint',w=>{w.survey[0].push('constraint');w.survey[1].push('. > 0');},'unsupported_column'],['dynamic required',w=>w.survey[1][6]="${loan} = 'yes'",'select_required'],['required text',w=>w.survey[3][6]='yes','required_text_unsupported'],['optional select',w=>w.survey[1][6]='','select_required'],['numeric comparison',w=>w.survey[3][7]='${loan} > 1','relevance_syntax'],['not equal',w=>w.survey[3][7]="${track} != 'print'",'relevance_syntax'],['empty comparison',w=>w.survey[3][7]="${track} = ''",'relevance_value'],['text controller',w=>w.survey[4][7]="${print_experience} = 'a'",'earlier_select_only'],['later controller',w=>w.survey[3][7]="${pickup} = 'morning'",'earlier_select_only'],['unknown code',w=>w.survey[3][7]="${track} = 'missing'",'unknown_choice'],['substitution',w=>w.survey[9][2]='You chose ${track}','plain_text'],['HTML label',w=>w.survey[9][2]='<b>Hello</b>','plain_text'],['external choices',w=>w.survey[1][0]='select_one_from_file tracks.csv','unsupported_type'],['filter',w=>{w.survey[0].push('choice_filter');w.survey[1].push('region=1');},'unsupported_column'],['media',w=>{w.survey[0].push('media::image');w.survey[1].push('a.png');},'unsupported_column'],['duplicate source name',w=>w.survey[2][1]='track','question_name'],['too many questions',w=>{for(let i=0;i<22;i++)w.survey.push(['text',`e${i}`,'Extra','追加','','','','']);},'question_limit']
])test(`reject ${label}`,()=>rejects(change,code));
test('reachable history cap is hard, not truncation',()=>assert.throws(()=>compileForm(parseForm(workshop),{historyLimit:5}),e=>e.code==='history_limit'));
test('card cap is hard, not truncation',()=>assert.throws(()=>compileForm(parseForm(workshop),{cardLimit:11}),e=>e.code==='card_limit'));
test('512-history boundary accepts 9 binary routing controllers; 1024 rejects',()=>{const build=n=>({survey:[['type','name','label','required','relevant'],...Array.from({length:n},(_,i)=>['select_one yn',`a${i}`,`Choice ${i}`,'yes','']),['note','last','Last','',Array.from({length:n},(_,i)=>`\${a${i}} = 'yes'`).join(' or ')]],choices:[['list_name','name','label'],['yn','yes','Yes'],['yn','no','No']]});assert.equal(compileTables(build(9)).counts.histories,512);assert.throws(()=>compileTables(build(10)),e=>e.code==='history_limit');});
