import {openZip} from './zip.mjs';
import sax from 'sax';
import {RouteError} from './core.mjs';
const fail=(code,detail)=>{throw new RouteError(code,detail)};
function parseXml(text){if(text.length>8*1024*1024||/<!DOCTYPE|<!ENTITY/i.test(text))fail('xml_unsafe','DTD or oversized XML');const p=sax.parser(true,{xmlns:true,trim:false});let root=null,stack=[];p.onopentag=t=>{if(stack.length>40)fail('xml_depth','XML');const n={tag:t.local,uri:t.uri,attrsNS:Object.fromEntries(Object.values(t.attributes).map(a=>[`${a.uri}|${a.local}`,a.value])),attrs:Object.fromEntries(Object.values(t.attributes).map(a=>[a.name,a.value])),children:[],text:''};if(stack.length)stack.at(-1).children.push(n);else if(root)fail('xml_invalid','Multiple roots');else root=n;stack.push(n);};p.ontext=t=>{if(stack.length)stack.at(-1).text+=t;};p.oncdata=t=>{if(stack.length)stack.at(-1).text+=t;};p.onclosetag=()=>stack.pop();p.onerror=()=>fail('xml_invalid','Invalid XML');p.write(text).close();return root;}
const all=(node,tag)=>node?.children.filter(c=>c.tag===tag)||[];
const child=(node,tag)=>all(node,tag)[0];
const textContent=n=>n?n.text+n.children.map(textContent).join(''):'';
function cellText(n){if(!n)return '';if(n.children.some(x=>!['t','r','rPh','phoneticPr'].includes(x.tag)))fail('cell_structure','Unsupported string child');return n.children.filter(x=>x.tag==='t'||x.tag==='r').map(x=>x.tag==='t'?x.text:all(x,'t').map(t=>t.text).join('')).join('');}
const column=r=>{const m=/^([A-Z]{1,3})([1-9][0-9]*)$/.exec(r||'');if(!m)fail('cell_reference',r);let i=0;for(const c of m[1])i=i*26+c.charCodeAt(0)-64;if(i>64||Number(m[2])>1000)fail('sheet_limit',r);return [i-1,Number(m[2])-1];};
export async function readXlsx(input){const bytes=input instanceof Uint8Array?input:new Uint8Array(input),zip=openZip(bytes),names=zip.names;if(names.some(n=>/vbaProject|externalLinks|connections\.xml|queryTables/i.test(n)))fail('xlsx_features','Macros, links or connections');async function read(name){let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(zip.read(name));}catch(e){if(e instanceof RouteError)throw e;fail('xml_invalid','Invalid UTF-8');}const root=parseXml(text),expected=name==='[Content_Types].xml'?'http://schemas.openxmlformats.org/package/2006/content-types':name.endsWith('.rels')?'http://schemas.openxmlformats.org/package/2006/relationships':'http://schemas.openxmlformats.org/spreadsheetml/2006/main';const check=n=>{if(n.uri!==expected)fail('xml_namespace',name);for(const c of n.children)check(c);};if(!root)fail('xml_invalid',name);check(root);return root;}
 const types=await read('[Content_Types].xml');if(types.tag!=='Types')fail('xlsx_invalid','Content types');const packageRels=await read('_rels/.rels');if(packageRels.tag!=='Relationships')fail('xlsx_invalid','Package relationships');const ids=packageRels.children.map(r=>r.attrs.Id);if(ids.some(x=>!x)||new Set(ids).size!==ids.length)fail('duplicate_relationship','Package');const office=packageRels.children.filter(r=>/\/officeDocument$/.test(r.attrs.Type||''));if(office.length!==1||office[0].attrs.TargetMode==='External'||!['xl/workbook.xml','/xl/workbook.xml'].includes(office[0].attrs.Target))fail('xlsx_invalid','Office document relationship');
 const book=await read('xl/workbook.xml');if(book.tag!=='workbook'||all(book,'sheets').length!==1)fail('xlsx_invalid','workbook');const rels=await read('xl/_rels/workbook.xml.rels');const relmap=new Map();for(const r of rels.children){if(!r.attrs.Id||relmap.has(r.attrs.Id))fail('duplicate_relationship',r.attrs.Id||'Missing ID');if(r.attrs.TargetMode==='External')fail('external_relationship',r.attrs.Target);let t=r.attrs.Target||'';if(t.startsWith('/'))t=t.slice(1);else t='xl/'+t;if(t.split('/').some(x=>x==='..'||x==='.'))fail('relationship_path',t);relmap.set(r.attrs.Id,t);}
 let strings=[];if(zip.has('xl/sharedStrings.xml')){const root=await read('xl/sharedStrings.xml');strings=all(root,'si').map(cellText);if(strings.length>3000)fail('string_limit','3000');}
 const tables=Object.create(null);for(const sh of all(child(book,'sheets'),'sheet')){const name=sh.attrs.name;if(Object.hasOwn(tables,name))fail('duplicate_sheet',name);const target=relmap.get(sh.attrsNS['http://schemas.openxmlformats.org/officeDocument/2006/relationships|id']);if(!target)fail('xlsx_part',name);const root=await read(target);if(root.tag!=='worksheet'||all(root,'sheetData').length!==1)fail('xlsx_invalid','Single worksheet sheetData required');const matrix=[];const occupied=new Set();for(const row of all(child(root,'sheetData'),'row'))for(const c of all(row,'c')){const [x,y]=column(c.attrs.r);if(occupied.has(c.attrs.r))fail('duplicate_cell',c.attrs.r);occupied.add(c.attrs.r);if(all(c,'v').length>1||all(c,'is').length>1||c.children.some(x=>!['v','f','is'].includes(x.tag)))fail('cell_structure',`${name}!${c.attrs.r}`);if(child(c,'f'))fail('formula_cell',`${name}!${c.attrs.r}`);let value='';const v=textContent(child(c,'v'));switch(c.attrs.t){case 's':{if(!/^\d+$/.test(v)||Number(v)>=strings.length)fail('string_index',v);value=strings[Number(v)];break;}case 'inlineStr':if(child(c,'v'))fail('cell_structure',c.attrs.r);value=cellText(child(c,'is'));break;case 'str':value=v;break;case undefined:case 'n':if(v!=='')value=Number(v);break;default:fail('cell_type',`${name}!${c.attrs.r}`);}if(typeof value==='string'&&/_x[0-9a-f]{4}_/i.test(value))fail('ooxml_escape',`${name}!${c.attrs.r}`);if(typeof value==='string'&&value.length>2000)fail('cell_length',`${name}!${c.attrs.r}`);matrix[y]??=[];matrix[y][x]=value;}
 tables[name]=Array.from({length:matrix.length},(_,i)=>Array.from({length:matrix[i]?.length||0},(_,j)=>matrix[i][j]??''));}
 return tables;
}
