import pako from 'pako';
import {RouteError} from './core.mjs';
const fail=(code,detail)=>{throw new RouteError(code,detail)};
const MAX_INPUT=8*1024*1024,MAX_EXPANDED=24*1024*1024,MAX_PART=8*1024*1024;
const crcTable=Uint32Array.from({length:256},(_,i)=>{for(let k=0;k<8;k++)i=(i&1)?0xedb88320^(i>>>1):i>>>1;return i>>>0;});
const crc32=bytes=>{let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;};
/** Parse ZIP structure before any decompression; inflate only requested parts with actual-byte bounds. */
export function openZip(bytes){if(bytes.length>MAX_INPUT)fail('file_size','8 MiB');if(bytes.length<22)fail('zip_invalid','Missing central directory');const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),u16=i=>view.getUint16(i,true),u32=i=>view.getUint32(i,true),decode=new TextDecoder('utf-8',{fatal:true});let end=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(u32(i)===0x06054b50&&i+22+u16(i+20)===bytes.length){end=i;break;}if(end<0)fail('zip_invalid','Missing central directory');const count=u16(end+10),offset=u32(end+16),size=u32(end+12);if(count>256||count!==u16(end+8)||offset+size!==end||u16(end+4)||u16(end+6)||count===65535)fail('zip_limit','Unsupported or excessive ZIP structure');const entries=new Map(),ranges=[];let p=offset,totalDeclared=0;
 for(let i=0;i<count;i++){if(p+46>offset+size||u32(p)!==0x02014b50)fail('zip_invalid','Directory entry');const flags=u16(p+8),method=u16(p+10),crc=u32(p+16),compressed=u32(p+20),expanded=u32(p+24),nl=u16(p+28),el=u16(p+30),cl=u16(p+32),local=u32(p+42);if(flags&~0x80e)fail('zip_encrypted','Unsupported ZIP flags');if(![0,8].includes(method))fail('zip_method','Compression');if(expanded>MAX_EXPANDED||totalDeclared+expanded>MAX_EXPANDED)fail('zip_limit','Expanded 24 MiB limit');totalDeclared+=expanded;if(p+46+nl+el+cl>offset+size)fail('zip_invalid','Directory bounds');let name;try{name=decode.decode(bytes.subarray(p+46,p+46+nl));}catch{fail('zip_path','Invalid UTF-8');}if(!name||name.includes('\\')||name.startsWith('/')||name.split('/').some(x=>x==='..')||entries.has(name))fail('zip_path',name);
 if(local+30>offset||u32(local)!==0x04034b50)fail('zip_invalid','Local header');const lnl=u16(local+26),lel=u16(local+28),dataStart=local+30+lnl+lel,dataEnd=dataStart+compressed;if(dataEnd>offset||u16(local+6)!==flags||u16(local+8)!==method)fail('zip_invalid','Local/central mismatch');let localName;try{localName=decode.decode(bytes.subarray(local+30,local+30+lnl));}catch{fail('zip_path','Invalid local name');}if(localName!==name)fail('zip_path','Local/central names differ');let recordEnd=dataEnd;
 if(flags&8){const sig=dataEnd+4<=offset&&u32(dataEnd)===0x08074b50?4:0;if(dataEnd+sig+12>offset||u32(dataEnd+sig)!==crc||u32(dataEnd+sig+4)!==compressed||u32(dataEnd+sig+8)!==expanded)fail('zip_invalid','Data descriptor');recordEnd=dataEnd+sig+12;for(const [at,want] of [[14,crc],[18,compressed],[22,expanded]])if(u32(local+at)!==0&&u32(local+at)!==want)fail('zip_invalid','Local descriptor mismatch');}
 else if(u32(local+14)!==crc||u32(local+18)!==compressed||u32(local+22)!==expanded)fail('zip_invalid','Local/central sizes differ');if(method===0&&compressed!==expanded)fail('zip_invalid','Stored size');ranges.push([local,recordEnd]);entries.set(name,{name,method,crc,compressed,expanded,dataStart,dataEnd});p+=46+nl+el+cl;
 }
 if(p!==offset+size)fail('zip_invalid','Directory size');ranges.sort((a,b)=>a[0]-b[0]);for(let i=1;i<ranges.length;i++)if(ranges[i][0]<ranges[i-1][1])fail('zip_invalid','Overlapping entries');let actualTotal=0;const cache=new Map();
 return {names:[...entries.keys()],has:name=>entries.has(name),read(name){if(cache.has(name))return cache.get(name);const e=entries.get(name);if(!e)fail('xlsx_part',name);let length=0,chunks=[];const accept=chunk=>{length+=chunk.length;actualTotal+=chunk.length;if(length>MAX_PART||actualTotal>MAX_EXPANDED||length>e.expanded)fail('zip_limit','Actual decompressed byte limit');chunks.push(new Uint8Array(chunk));};if(e.method===0)accept(bytes.subarray(e.dataStart,e.dataEnd));else{const inflater=new pako.Inflate({raw:true,chunkSize:16384});inflater.onData=accept;try{inflater.push(bytes.subarray(e.dataStart,e.dataEnd),true);}catch(error){if(error instanceof RouteError)throw error;fail('zip_invalid','Inflation');}if(inflater.err||inflater.strm.total_in!==e.compressed)fail('zip_invalid','Deflate data or trailing bytes');}if(length!==e.expanded)fail('zip_invalid','Actual expanded size differs');const result=new Uint8Array(length);let at=0;for(const chunk of chunks){result.set(chunk,at);at+=chunk.length;}if(crc32(result)!==e.crc)fail('zip_invalid','CRC mismatch');cache.set(name,result);return result;}};
}
