import {readXlsx} from '../src/xlsx.mjs';
import {availableLanguages,compileTables} from '../src/core.mjs';
import {validatePrintLayout,renderBookletHtml,renderAnswerSheetHtml,createPdf} from '../src/print.mjs';
import {messages} from './messages.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let lang='ja',tables=null,manifest=null,filename='',epoch=0,active='END',trace=[],noticeKey=null,noticeDetail='',busy=false;
const t=k=>messages[lang][k]||k;
function el(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e;}
function notice(key,detail='',error=false){noticeKey=key;noticeDetail=detail;const p=$('#notice');p.hidden=!key;p.className=error?'error':'';p.textContent=key?`${t(key)}${detail?': '+detail:''}${error?' — '+t('errorHint'):''}`:'';}
function clearOutput(){manifest=null;active='END';trace=[];$('#results').hidden=true;$('#active-card').replaceChildren();$('#card-list').replaceChildren();$('#trace').replaceChildren();}
function redraw(){document.documentElement.lang=lang;$$('[data-t]').forEach(e=>e.textContent=t(e.dataset.t));$('#file-name').textContent=filename||t('fileEmpty');if(noticeKey)notice(noticeKey,noticeDetail,$('#notice').classList.contains('error'));if(manifest)showManifest(false);}
function save(bytes,name,type){const blob=new Blob([bytes],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const sampleBytes=()=>Uint8Array.from(atob(__SAMPLE_BASE64__),c=>c.charCodeAt(0));
async function load(input,name){const job=++epoch;clearOutput();tables=null;filename=name;$('#file-name').textContent=name;$('#compile').disabled=true;$('#form-language').disabled=true;$('#form-language').replaceChildren();notice('loading');try{const bytes=typeof input==='function'?await input():input;const parsed=await readXlsx(bytes);if(job!==epoch)return;tables=parsed;const languages=availableLanguages(parsed);for(const value of languages){const o=el('option','',value);o.value=value;$('#form-language').append(o);}const preferred=languages.find(x=>lang==='ja'?/日本語|\(ja\)/.test(x):/English|\(en\)/.test(x));if(preferred)$('#form-language').value=preferred;$('#form-language').disabled=false;$('#compile').disabled=false;notice('loaded');}catch(e){if(job!==epoch)return;notice('error',`${e.code||'invalid_file'} · ${e.detail||e.message}`,true);}}
async function compile(){if(!tables)return;const job=++epoch;clearOutput();$('#compile').disabled=true;notice('building');try{await new Promise(r=>setTimeout(r,0));const result=compileTables(tables,$('#form-language').value);const layout=validatePrintLayout(result);if(!layout.ok)throw Object.assign(new Error(layout.errors.join('; ')),{code:'print_layout'});if(job!==epoch)return;manifest=result;active=result.start;trace=[];showManifest();notice('ready');}catch(e){if(job===epoch)notice('error',`${e.code||'invalid_form'} · ${e.detail||e.message}`,true);}finally{if(job===epoch)$('#compile').disabled=!tables;}}
function destination(id){if(id==='END')return t('end');const card=manifest.cards.find(c=>c.id===id);return `${id} · ${t('page')} ${card.page}`;}
function showManifest(resetWalk=true){$('#results').hidden=false;$('#form-title').textContent=manifest.title;$('#stats').replaceChildren();for(const [key,value] of [['sourceQuestions',manifest.counts.questions],['histories',manifest.counts.histories],['cards',manifest.counts.cards],['pages',manifest.counts.pages],['answerPages',manifest.counts.answerSheetPages]]){const s=el('div','stat');s.append(el('strong','',String(value)),el('span','',t(key)));$('#stats').append(s);}$('#unreachable').hidden=!manifest.unreachable.length;$('#unreachable').textContent=`${t('unreachable')}: ${manifest.unreachable.join(', ')}`;renderWalk();$('#card-list').replaceChildren();for(const card of manifest.cards){const box=el('article','mini-card');box.append(el('h4','',`${card.id} · ${t('page')} ${card.page}`),el('small','',`Q${card.questionNumber} / ${card.source}`),el('p','',card.label));const list=el('ul');for(const x of card.options||[{label:t('next'),next:card.next}])list.append(el('li','',`${x.label} → ${destination(x.next)}`));box.append(list);$('#card-list').append(box);}if(resetWalk)$('#active-card').focus({preventScroll:true});}
function advance(next,answer){const current=manifest.cards.find(c=>c.id===active);trace.push({id:active,source:current.source,answer:answer||''});active=next;renderWalk();}
function renderWalk(){const box=$('#active-card');box.replaceChildren();box.tabIndex=-1;box.dataset.card=active;if(active==='END'){box.append(el('p','active-title',t('end')),el('p','active-hint',t('endHint')));}else{const card=manifest.cards.find(c=>c.id===active);box.append(el('p','active-meta',`${card.id} · ${t('page')} ${card.page} · Q${card.questionNumber} / ${card.source}`));if(card.groups?.length)box.append(el('p','active-hint',card.groups.join(' / ')));box.append(el('h4','active-title',card.label));if(card.hint)box.append(el('p','active-hint',card.hint));const options=el('div','active-options');if(card.kind==='select_one'){for(const option of card.options){const b=el('button','secondary');b.dataset.value=option.value;b.append(el('span','',option.label),el('small','',`→ ${destination(option.next)}`));b.addEventListener('click',()=>advance(option.next,option.label));options.append(b);}}else{box.append(el('p','active-hint',t(card.kind==='note'?'readNote':'writeAnswer')));const b=el('button','primary',`${t('next')} → ${destination(card.next)}`);b.addEventListener('click',()=>advance(card.next));options.append(b);}box.append(options);}$('#trace').replaceChildren();for(const entry of trace){const li=el('li');li.append(el('strong','',entry.id),el('small','',entry.source));if(entry.answer)li.append(el('span','',entry.answer));$('#trace').append(li);}}
$('#language').addEventListener('change',e=>{lang=e.target.value;redraw();});
$('#source-input').addEventListener('change',e=>{const f=e.target.files[0];if(f)load(()=>f.arrayBuffer(),f.name);});
$('#sample').addEventListener('click',()=>load(sampleBytes(),'workshop.xlsx'));
$('#sample-download').addEventListener('click',()=>save(sampleBytes(),'workshop.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'));
$('#compile').addEventListener('click',compile);
$('#form-language').addEventListener('change',()=>{epoch++;clearOutput();$('#compile').disabled=!tables;notice('loaded');});
$('#reset').addEventListener('click',()=>{epoch++;tables=null;filename='';$('#source-input').value='';$('#form-language').replaceChildren();$('#form-language').disabled=true;$('#compile').disabled=true;clearOutput();notice(null);redraw();});
$('#restart').addEventListener('click',()=>{if(manifest){active=manifest.start;trace=[];renderWalk();}});
$('#download-routes').addEventListener('click',()=>{if(manifest)save(JSON.stringify(manifest,null,2),'routeleaf.routes.json','application/json');});
$('#download-html').addEventListener('click',()=>{if(manifest)save(renderBookletHtml(manifest),'routeleaf-booklet.html','text/html;charset=utf-8');});
$('#download-answers').addEventListener('click',()=>{if(manifest)save(renderAnswerSheetHtml(manifest),'routeleaf-answer-sheet.html','text/html;charset=utf-8');});
$('#download-pdf').addEventListener('click',async()=>{if(!manifest||busy)return;const output=manifest,job=epoch;busy=true;$('#download-pdf').disabled=true;notice('pdfBusy');try{const bytes=await createPdf(output);if(job===epoch&&manifest===output){save(bytes,'routeleaf-booklet.pdf','application/pdf');notice('pdfReady');}}catch(e){if(job===epoch)notice('error',`print_layout · ${e.message}`,true);}finally{busy=false;$('#download-pdf').disabled=false;}});
redraw();
